#!/bin/sh
# Check mm file "$1" using metamath C implementation.
# Return 0 (true) if it's okay and non-zero (error) if there's a problem.
# We only report on errors, not on warnings.

metamath "read $1" 'verify proof *' exit | tee mm.log && [ `egrep -q '?Error' < mm.log; echo $?` -eq 1 ]
